"""Tactus domain model.

Pure value types and entities for the Work Order lifecycle, its dependency
graph, and the execution-admission boundary. This package deliberately has no
I/O, framework or persistence dependencies so that the core invariants stay
portable (including a possible future Rust implementation of a
reliability-critical component).
"""

from .admission import (
    AdmissionDecision,
    AdmissionError,
    AdmissionFacts,
    ClaimToken,
    ClaimUnavailableError,
    DagsterRunId,
    DomainClaim,
    DurableAdmissionRequest,
    DurableAttempt,
    DurableExecutionAdmissionPort,
    DuplicateExecutionAttemptError,
    ExecutionAdmission,
    ExecutionAdmissionPort,
    ExecutionAttempt,
    ExecutionAttemptId,
    ExecutionIntentId,
    ExecutionRequest,
    ExecutionRequestMismatchError,
    FencingError,
    IneligibleWorkOrderError,
    ImmutableRecordConflictError,
    ResultApplicationError,
    ResultRecord,
    SourceRevision,
    StaleWorkOrderRevisionError,
    SubmissionId,
    SubmissionRecord,
    UnknownExecutionAttemptError,
    WorkOrderRevision,
)
from .dependency import (
    CyclicDependencyError,
    DependencyChangeRecord,
    DependencyError,
    DependencyGraph,
    DuplicateDependencyError,
    MissingDependencyError,
    SelfDependencyError,
    WorkOrderDependency,
)
from .blockers import (
    AlreadyResolvedBlockerError,
    BlockReason,
    Blocker,
    BlockerError,
    BlockerId,
    BlockerSet,
    DuplicateBlockerError,
    InvalidBlockerError,
    ResolutionCondition,
    ResolutionKind,
    UnknownBlockerError,
    coerce_blocker_id,
    default_resolution_condition,
)
from .observation import FailureObservation
from .readiness import (
    AuthenticatedHold,
    ReadinessEvaluation,
    ReadinessFacts,
    apply_readiness,
    derive_blockers,
    evaluate_readiness,
    readiness_status,
)
from .records import TransitionAuthority, TransitionRecord
from .work_order import (
    IllegalTransitionError,
    InvalidReadinessError,
    OpenStatus,
    WorkOrder,
    WorkOrderId,
    WorkOrderState,
)

__all__ = [
    "AdmissionDecision",
    "AdmissionError",
    "AdmissionFacts",
    "AlreadyResolvedBlockerError",
    "AuthenticatedHold",
    "BlockReason",
    "Blocker",
    "BlockerError",
    "BlockerId",
    "BlockerSet",
    "CyclicDependencyError",
    "DagsterRunId",
    "DependencyChangeRecord",
    "DependencyError",
    "DependencyGraph",
    "DuplicateBlockerError",
    "DuplicateDependencyError",
    "DuplicateExecutionAttemptError",
    "ExecutionAdmission",
    "ExecutionAdmissionPort",
    "ExecutionAttempt",
    "ExecutionAttemptId",
    "ExecutionIntentId",
    "ExecutionRequest",
    "ExecutionRequestMismatchError",
    "FailureObservation",
    "IllegalTransitionError",
    "IneligibleWorkOrderError",
    "InvalidBlockerError",
    "InvalidReadinessError",
    "MissingDependencyError",
    "OpenStatus",
    "ReadinessEvaluation",
    "ReadinessFacts",
    "ResolutionCondition",
    "ResolutionKind",
    "SelfDependencyError",
    "TransitionAuthority",
    "TransitionRecord",
    "UnknownBlockerError",
    "UnknownExecutionAttemptError",
    "WorkOrder",
    "WorkOrderDependency",
    "WorkOrderId",
    "WorkOrderState",
    "apply_readiness",
    "coerce_blocker_id",
    "default_resolution_condition",
    "derive_blockers",
    "evaluate_readiness",
    "readiness_status",
]

# Durable admission contracts.
__all__ += [
    "ClaimToken",
    "ClaimUnavailableError",
    "DomainClaim",
    "DurableAdmissionRequest",
    "DurableAttempt",
    "DurableExecutionAdmissionPort",
    "FencingError",
    "ImmutableRecordConflictError",
    "ResultApplicationError",
    "ResultRecord",
    "SourceRevision",
    "StaleWorkOrderRevisionError",
    "SubmissionId",
    "SubmissionRecord",
    "WorkOrderRevision",
]
